In [1]:
import numpy as np
import pandas as pd
import requests
import plotly.express as px
from dash import Dash, html, dcc

In [2]:
url = 'https://api.congress.gov/v3/member'
params = {'api_key': 'DEMO_KEY'}
r = requests.get(url, params = params)
r.json()

{'members': [{'bioguideId': 'G000607',
   'depiction': {'imageUrl': 'https://www.congress.gov/img/member/6a29d4f81c6ce0de6fbae1f7_200.jpg'},
   'district': 1,
   'name': 'Gallagher, James',
   'partyName': 'Republican',
   'state': 'California',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-08-27T07:40:45Z',
   'url': 'https://api.congress.gov/v3/member/G000607?format=json'},
  {'bioguideId': 'M001246',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/69eb9743277642362f6112ce_200.jpg'},
   'district': 11,
   'name': 'Mejia, Analilia',
   'partyName': 'Democratic',
   'state': 'New Jersey',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-08-27T07:40:45Z',
   'url': 'https://api.congress.gov/v3/member/M001246?format=json'},
  {'bioguideId': 'F000485',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/69eb95e5277642362f6112c5_200.jpg'},
   'district': 14,
   'name': 'Fuller, Clay',
   'partyName': 'Republican',
   'state': 'Georgia',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-08-27T07:40:45Z',
   'url': 'https://api.congress.gov/v3/member/F000485?format=json'},
  {'bioguideId': 'M001245',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/698206b2eb30d3271899373e_200.jpg'},
   'district': 18,
   'name': 'Menefee, Christian D.',
   'partyName': 'Democratic',
   'state': 'Texas',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2026}]},
   'updateDate': '2026-08-27T07:40:45Z',
   'url': 'https://api.congress.gov/v3/member/M001245?format=json'},
  {'bioguideId': 'V000139',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6931b7d5f478c0f1228e9abe_200.jpg'},
   'district': 7,
   'name': 'Van Epps, Matt',
   'partyName': 'Republican',
   'state': 'Tennessee',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-08-27T07:40:45Z',
   'url': 'https://api.congress.gov/v3/member/V000139?format=json'},
  {'bioguideId': 'P000622',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67efdb991b05a5a598f7fde9_200.jpg'},
   'district': 1,
   'name': 'Patronis, Jimmy',
   'partyName': 'Republican',
   'state': 'Florida',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-08-27T07:40:45Z',
   'url': 'https://api.congress.gov/v3/member/P000622?format=json'},
  {'bioguideId': 'F000484',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67efda8c1b05a5a598f7fde0_200.jpg'},
   'district': 6,
   'name': 'Fine, Randy',
   'partyName': 'Republican',
   'state': 'Florida',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-08-27T07:40:45Z',
   'url': 'https://api.congress.gov/v3/member/F000484?format=json'},
  {'bioguideId': 'V000138',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6774617a0b34857ecc9091b5_200.jpg'},
   'district': 7,
   'name': 'Vindman, Eugene Simon',
   'partyName': 'Democratic',
   'state': 'Virginia',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-08-27T07:40:45Z',
   'url': 'https://api.congress.gov/v3/member/V000138?format=json'},
  {'bioguideId': 'T000490',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/677460190b34857ecc9091a3_200.jpg'},
   'district': 2,
   'name': 'Taylor, David J.',
   'partyName': 'Republican',
   'state': 'Ohio',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-08-27T07:40:45Z',
   'url': 'https://api.congress.gov/v3/member/T000490?format=json'},
  {'bioguideId': 'S001230',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6797be8bc75fbc6f720e476a_200.jpg'},
   'district': 10,
   'name': 'Subramanyam, Suhas',
   'partyName': 'Democratic',
   'state': 'Virginia',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-08-27T07:40:45Z',
   'url': 'https://api.congress.gov/v3/member/S001230?format=json'},
  {'bioguideId': 'S001229',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67745f0e0b34857ecc90918b_200.jpg'},
   'district': 6,
   'name': 'Shreve, Jefferson',
   'partyName': 'Republican',
   'state': 'Indiana',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-08-27T07:40:45Z',
   'url': 'https://api.congress.gov/v3/member/S001229?format=json'},
  {'bioguideId': 'S001228',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67745ec50b34857ecc909185_200.jpg'},
   'district': 2,
   'name': 'Schmidt, Derek',
   'partyName': 'Republican',
   'state': 'Kansas',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-08-27T07:40:45Z',
   'url': 'https://api.congress.gov/v3/member/S001228?format=json'},
  {'bioguideId': 'R000622',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67745e360b34857ecc909179_200.jpg'},
   'district': 19,
   'name': 'Riley, Josh',
   'partyName': 'Democratic',
   'state': 'New York',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-08-27T07:40:45Z',
   'url': 'https://api.congress.gov/v3/member/R000622?format=json'},
  {'bioguideId': 'P000621',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67745d3b0b34857ecc909167_200.jpg'},
   'district': 9,
   'name': 'Pou, Nellie',
   'partyName': 'Democratic',
   'state': 'New Jersey',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-08-27T07:40:45Z',
   'url': 'https://api.congress.gov/v3/member/P000621?format=json'},
  {'bioguideId': 'O000176',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/6a3974507d3b72f27fb69f0c_200.jpg'},
   'district': 2,
   'name': 'Olszewski, Johnny',
   'partyName': 'Democratic',
   'state': 'Maryland',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-08-27T07:40:45Z',
   'url': 'https://api.congress.gov/v3/member/O000176?format=json'},
  {'bioguideId': 'M001240',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67744e930b34857ecc90914f_200.jpg'},
   'district': 6,
   'name': 'McDowell, Addison P.',
   'partyName': 'Republican',
   'state': 'North Carolina',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-08-27T07:40:45Z',
   'url': 'https://api.congress.gov/v3/member/M001240?format=json'},
  {'bioguideId': 'M001239',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67744ba20b34857ecc909149_200.jpg'},
   'district': 5,
   'name': 'McGuire, John J.',
   'partyName': 'Republican',
   'state': 'Virginia',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-08-27T07:40:45Z',
   'url': 'https://api.congress.gov/v3/member/M001239?format=json'},
  {'bioguideId': 'M001237',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/69d7f4ee7304cef7a0c977a8_200.jpg'},
   'district': 8,
   'name': 'McDonald Rivet, Kristen',
   'partyName': 'Democratic',
   'state': 'Michigan',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-08-27T07:40:45Z',
   'url': 'https://api.congress.gov/v3/member/M001237?format=json'},
  {'bioguideId': 'M001236',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/67744a540b34857ecc909137_200.jpg'},
   'district': 14,
   'name': 'Moore, Tim',
   'partyName': 'Republican',
   'state': 'North Carolina',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-08-27T07:40:45Z',
   'url': 'https://api.congress.gov/v3/member/M001236?format=json'},
  {'bioguideId': 'M001235',
   'depiction': {'attribution': 'Image courtesy of the Member',
    'imageUrl': 'https://www.congress.gov/img/member/677449fd0b34857ecc909131_200.jpg'},
   'district': 2,
   'name': 'Moore, Riley M.',
   'partyName': 'Republican',
   'state': 'West Virginia',
   'terms': {'item': [{'chamber': 'House of Representatives',
      'startYear': 2025}]},
   'updateDate': '2026-08-27T07:40:45Z',
   'url': 'https://api.congress.gov/v3/member/M001235?format=json'}],
 'pagination': {'count': 2694,
  'next': 'https://api.congress.gov/v3/member?offset=20&limit=20&format=json'},
 'request': {'contentType': 'application/json', 'format': 'json'}}

In [3]:
memberdata = pd.json_normalize(r.json(), record_path=['members'])
memberdata

,bioguideId,district,name,partyName,state,updateDate,url,depiction.imageUrl,terms.item,depiction.attribution
0,G000607,1,"Gallagher, James",Republican,California,2026-08-27T07:40:45Z,https://api.congress.gov/v3/member/G000607?for...,https://www.congress.gov/img/member/6a29d4f81c...,"[{'chamber': 'House of Representatives', 'star...",NaN
1,M001246,11,"Mejia, Analilia",Democratic,New Jersey,2026-08-27T07:40:45Z,https://api.congress.gov/v3/member/M001246?for...,https://www.congress.gov/img/member/69eb974327...,"[{'chamber': 'House of Representatives', 'star...",Image courtesy of the Member
2,F000485,14,"Fuller, Clay",Republican,Georgia,2026-08-27T07:40:45Z,https://api.congress.gov/v3/member/F000485?for...,https://www.congress.gov/img/member/69eb95e527...,"[{'chamber': 'House of Representatives', 'star...",Image courtesy of the Member
3,M001245,18,"Menefee, Christian D.",Democratic,Texas,2026-08-27T07:40:45Z,https://api.congress.gov/v3/member/M001245?for...,https://www.congress.gov/img/member/698206b2eb...,"[{'chamber': 'House of Representatives', 'star...",Image courtesy of the Member
4,V000139,7,"Van Epps, Matt",Republican,Tennessee,2026-08-27T07:40:45Z,https://api.congress.gov/v3/member/V000139?for...,https://www.congress.gov/img/member/6931b7d5f4...,"[{'chamber': 'House of Representatives', 'star...",Image courtesy of the Member
5,P000622,1,"Patronis, Jimmy",Republican,Florida,2026-08-27T07:40:45Z,https://api.congress.gov/v3/member/P000622?for...,https://www.congress.gov/img/member/67efdb991b...,"[{'chamber': 'House of Representatives', 'star...",Image courtesy of the Member
6,F000484,6,"Fine, Randy",Republican,Florida,2026-08-27T07:40:45Z,https://api.congress.gov/v3/member/F000484?for...,https://www.congress.gov/img/member/67efda8c1b...,"[{'chamber': 'House of Representatives', 'star...",Image courtesy of the Member
7,V000138,7,"Vindman, Eugene Simon",Democratic,Virginia,2026-08-27T07:40:45Z,https://api.congress.gov/v3/member/V000138?for...,https://www.congress.gov/img/member/6774617a0b...,"[{'chamber': 'House of Representatives', 'star...",Image courtesy of the Member
8,T000490,2,"Taylor, David J.",Republican,Ohio,2026-08-27T07:40:45Z,https://api.congress.gov/v3/member/T000490?for...,https://www.congress.gov/img/member/677460190b...,"[{'chamber': 'House of Representatives', 'star...",Image courtesy of the Member
9,S001230,10,"Subramanyam, Suhas",Democratic,Virginia,2026-08-27T07:40:45Z,https://api.congress.gov/v3/member/S001230?for...,https://www.congress.gov/img/member/6797be8bc7...,"[{'chamber': 'House of Representatives', 'star...",Image courtesy of the Member
10,S001229,6,"Shreve, Jefferson",Republican,Indiana,2026-08-27T07:40:45Z,https://api.congress.gov/v3/member/S001229?for...,https://www.congress.gov/img/member/67745f0e0b...,"[{'chamber': 'House of Representatives', 'star...",Image courtesy of the Member
11,S001228,2,"Schmidt, Derek",Republican,Kansas,2026-08-27T07:40:45Z,https://api.congress.gov/v3/member/S001228?for...,https://www.congress.gov/img/member/67745ec50b...,"[{'chamber': 'House of Representatives', 'star...",Image courtesy of the Member
12,R000622,19,"Riley, Josh",Democratic,New York,2026-08-27T07:40:45Z,https://api.congress.gov/v3/member/R000622?for...,https://www.congress.gov/img/member/67745e360b...,"[{'chamber': 'House of Representatives', 'star...",Image courtesy of the Member
13,P000621,9,"Pou, Nellie",Democratic,New Jersey,2026-08-27T07:40:45Z,https://api.congress.gov/v3/member/P000621?for...,https://www.congress.gov/img/member/67745d3b0b...,"[{'chamber': 'House of Representatives', 'star...",Image courtesy of the Member
14,O000176,2,"Olszewski, Johnny",Democratic,Maryland,2026-08-27T07:40:45Z,https://api.congress.gov/v3/member/O000176?for...,https://www.congress.gov/img/member/6a3974507d...,"[{'chamber': 'House of Representatives', 'star...",Image courtesy of the Member
15,M001240,6,"McDowell, Addison P.",Republican,North Carolina,2026-08-27T07:40:45Z,https://api.congress.gov/v3/member/M001240?for...,https://www.congress.gov/img/member/67744e930b...,"[{'chamber': 'House of Representatives', 'star...",Image courtesy of the Member
16,M001239,5,"McGuire, John J.",Republican,Virginia,2026-08-27T07:40:45Z,https://api.congress.gov/v3/member/M001239?for...,https://www.congress.gov/img/member/67744ba20b...,"[{'chamber': 'House of Representatives', 'star...",Image courtesy of the Member
17,M001237,8,"McDonald Rivet, Kristen",Democratic,Michigan,2026-08-27T07:40:45Z,https://api.congress.gov/v3/member/M001237?for...,https://www.congress.gov/img/member/69d7f4ee73...,"[{'chamber': 'House of Representatives', 'star...",Image courtesy of the Member
18,M001236,14,"Moore, Tim",Republican,North Carolina,2026-08-27T07:40:45Z,https://api.congress.gov/v3/member/M001236?for...,https://www.congress.gov/img/member/67744a540b...,"[{'chamber': 'House of Representatives', 'star...",Image courtesy of the Member
19,M001235,2,"Moore, Riley M.",Republican,West Virginia,2026-08-27T07:40:45Z,https://api.congress.gov/v3/member/M001235?for...,https://www.congress.gov/img/member/677449fd0b...,"[{'chamber': 'House of Representatives', 'star...",Image courtesy of the Member

In [4]:
member_parties = memberdata.groupby('partyName').size().reset_index()
member_parties = member_parties.rename({0:'count'}, axis=1)
member_parties

    partyName  count
0  Democratic      8
1  Republican     12

In [5]:
px.bar(member_parties, x='partyName', y='count')